In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("LLM_Analytics.xlsx")

In [3]:
df.head()

,User Name,Age Group,Country,Profession,AI / LLM Name,Plan Type,Primary Purpose,Usage Context,Usage Frequency,Daily Usage (Minutes),Device,Satisfaction Score,Response Quality Rating,Accuracy Rating,Would Recommend,Usage Date,Preferred AI Feature
0,Ella King,18–25,India,Student,DeepSeek,Free,Coding,Professional,Weekly,5,Laptop,5,5,5,No,2025-10-06,Fast Responses
1,Simran Wright,18–25,South Korea,Marketing Professional,ChatGPT,Free,Content Writing,Personal,Several Times a Week,34,Laptop,2,2,2,No,2025-06-08,Fast Responses
2,Karan Kumar,26–35,Malaysia,Teacher,Grok,Free,Study / Education,Academic,Daily,90,Mobile,5,5,5,Yes,2025-08-06,Easy to Use
3,Ava Lewis,18–25,India,Student,Gemini,Free,Content Writing,Professional,Daily,72,Mobile,4,4,5,Yes,2025-12-14,Fast Responses
4,Mia Jain,26–35,Italy,Designer,Gemini,Plus,Content Writing,Personal,Daily,79,Laptop,1,1,1,No,2025-03-06,Writing

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User Name                2000 non-null   str
 1   Age Group                2000 non-null   str
 2   Country                  2000 non-null   str
 3   Profession               2000 non-null   str
 4   AI / LLM Name            2000 non-null   str
 5   Plan Type                2000 non-null   str
 6   Primary Purpose          2000 non-null   str
 7   Usage Context            2000 non-null   str
 8   Usage Frequency          2000 non-null   str
 9   Daily Usage (Minutes)    2000 non-null   int64
 10  Device                   2000 non-null   str
 11  Satisfaction Score       2000 non-null   int64
 12  Response Quality Rating  2000 non-null   int64
 13  Accuracy Rating          2000 non-null   int64
 14  Would Recommend          2000 non-null   str
 15  Usage Date               2000 non-null   str
 16  Preferred AI Feature     2000 non-null   str
dtypes: int64(4), str(13)
memory usage: 265.8 KB

In [5]:
df.describe()

,Daily Usage (Minutes),Satisfaction Score,Response Quality Rating,Accuracy Rating
count,2000.000000,2000.000000,2000.000000,2000.000000
mean,67.887500,3.833500,3.788500,3.735000
std,37.627487,1.025819,1.097438,1.165098
min,5.000000,1.000000,1.000000,1.000000
25%,38.000000,3.000000,3.000000,3.000000
50%,67.500000,4.000000,4.000000,4.000000
75%,97.000000,5.000000,5.000000,5.000000
max,177.000000,5.000000,5.000000,5.000000

In [6]:
df.shape

(2000, 17)

In [7]:
df.isnull().sum()

User Name                  0
Age Group                  0
Country                    0
Profession                 0
AI / LLM Name              0
Plan Type                  0
Primary Purpose            0
Usage Context              0
Usage Frequency            0
Daily Usage (Minutes)      0
Device                     0
Satisfaction Score         0
Response Quality Rating    0
Accuracy Rating            0
Would Recommend            0
Usage Date                 0
Preferred AI Feature       0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df=df.apply(lambda x:x.str.strip() if x.dtype=='object'else x)

In [11]:
df["Usage Date"]=pd.to_datetime(df["Usage Date"],errors="coerce")

In [12]:
numeric_cols = ['Daily Usage (Minutes)', 'Satisfaction Score', 'Response Quality Rating', 'Accuracy Rating']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    print(df[numeric_cols].dtypes)

Daily Usage (Minutes)      int64
Satisfaction Score         int64
Response Quality Rating    int64
Accuracy Rating            int64
dtype: object
Daily Usage (Minutes)      int64
Satisfaction Score         int64
Response Quality Rating    int64
Accuracy Rating            int64
dtype: object
Daily Usage (Minutes)      int64
Satisfaction Score         int64
Response Quality Rating    int64
Accuracy Rating            int64
dtype: object
Daily Usage (Minutes)      int64
Satisfaction Score         int64
Response Quality Rating    int64
Accuracy Rating            int64
dtype: object

In [13]:
df['Month'] = df['Usage Date'].dt.month_name()
df['Year'] = df['Usage Date'].dt.year
df['Weekday'] = df['Usage Date'].dt.day_name()

df[['Usage Date', 'Month', 'Year', 'Weekday']].head()

  Usage Date     Month  Year    Weekday
0 2025-10-06   October  2025     Monday
1 2025-06-08      June  2025     Sunday
2 2025-08-06    August  2025  Wednesday
3 2025-12-14  December  2025     Sunday
4 2025-03-06     March  2025   Thursday

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   User Name                2000 non-null   str
 1   Age Group                2000 non-null   str
 2   Country                  2000 non-null   str
 3   Profession               2000 non-null   str
 4   AI / LLM Name            2000 non-null   str
 5   Plan Type                2000 non-null   str
 6   Primary Purpose          2000 non-null   str
 7   Usage Context            2000 non-null   str
 8   Usage Frequency          2000 non-null   str
 9   Daily Usage (Minutes)    2000 non-null   int64
 10  Device                   2000 non-null   str
 11  Satisfaction Score       2000 non-null   int64
 12  Response Quality Rating  2000 non-null   int64
 13  Accuracy Rating          2000 non-null   int64
 14  Would Recommend          2000 non-null   str
 15  Usage Date               2000 non-null   datetime64[us]
 16  Preferred AI Feature     2000 non-null   str
 17  Month                    2000 non-null   str
 18  Year                     2000 non-null   int32
 19  Weekday                  2000 non-null   str
dtypes: datetime64[us](1), int32(1), int64(4), str(14)
memory usage: 304.8 KB

In [15]:
df.isnull().sum()

User Name                  0
Age Group                  0
Country                    0
Profession                 0
AI / LLM Name              0
Plan Type                  0
Primary Purpose            0
Usage Context              0
Usage Frequency            0
Daily Usage (Minutes)      0
Device                     0
Satisfaction Score         0
Response Quality Rating    0
Accuracy Rating            0
Would Recommend            0
Usage Date                 0
Preferred AI Feature       0
Month                      0
Year                       0
Weekday                    0
dtype: int64

In [16]:
df.describe()

,Daily Usage (Minutes),Satisfaction Score,Response Quality Rating,Accuracy Rating,Usage Date,Year
count,2000.000000,2000.000000,2000.000000,2000.000000,2000,2000.0
mean,67.887500,3.833500,3.788500,3.735000,2025-07-05 16:45:50.400000,2025.0
min,5.000000,1.000000,1.000000,1.000000,2025-01-01 00:00:00,2025.0
25%,38.000000,3.000000,3.000000,3.000000,2025-04-01 00:00:00,2025.0
50%,67.500000,4.000000,4.000000,4.000000,2025-07-09 00:00:00,2025.0
75%,97.000000,5.000000,5.000000,5.000000,2025-10-11 00:00:00,2025.0
max,177.000000,5.000000,5.000000,5.000000,2025-12-31 00:00:00,2025.0
std,37.627487,1.025819,1.097438,1.165098,NaN,0.0

In [17]:
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].astype(str).str.strip()

C:\Users\kshama\AppData\Local\Temp\ipykernel_9272\3104867953.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [18]:
df['AI / LLM Name'] = df['AI / LLM Name'].str.title()

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
print("Unique Countries:", df['Country'].unique())
print("Unique Devices:", df['Device'].unique())

Unique Countries: <StringArray>
[         'India',    'South Korea',       'Malaysia',          'Italy',
      'Singapore',         'Mexico',         'France',         'Canada',
  'United States',          'Japan',    'Netherlands',            'UAE',
      'Australia',         'Sweden',      'Indonesia',        'Germany',
 'United Kingdom',        'Ireland',    'Philippines',         'Brazil',
          'China',   'South Africa',   'Saudi Arabia',          'Spain',
    'New Zealand',    'Switzerland']
Length: 26, dtype: str
Unique Devices: <StringArray>
['Laptop', 'Mobile', 'Desktop', 'Tablet']
Length: 4, dtype: str

In [21]:
print("Top 5 Usage Outliers:\n", df['Daily Usage (Minutes)'].nlargest(5))

Top 5 Usage Outliers:
 1004    177
1832    171
338     170
335     166
492     166
Name: Daily Usage (Minutes), dtype: int64

In [22]:
if 'Age' in df.columns:
    df = df[(df['Age'] >= 10) & (df['Age'] <= 90)]

In [23]:
print("\nFinal Data Types:\n", df.dtypes)

Final Data Types:
 User Name                             str
Age Group                             str
Country                               str
Profession                            str
AI / LLM Name                         str
Plan Type                             str
Primary Purpose                       str
Usage Context                         str
Usage Frequency                       str
Daily Usage (Minutes)               int64
Device                                str
Satisfaction Score                  int64
Response Quality Rating             int64
Accuracy Rating                     int64
Would Recommend                       str
Usage Date                 datetime64[us]
Preferred AI Feature                  str
Month                                 str
Year                                int32
Weekday                               str
dtype: object

In [24]:
df.to_csv("Ready_llm.csv",index=False, encoding='utf-8-sig')

In [25]:

!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in c:\users\kshama\appdata\local\programs\python\python311\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\kshama\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kshama\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pymysql in c:\users\kshama\appdata\local\programs\python\python311\lib\site-packages (1.2.0)

[notice] A new release of pip is available: 23.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from sqlalchemy import create_engine 
engine=create_engine("mysql+pymysql://root:12345@localhost/LLM")

In [27]:
df.to_sql( 
    name="ready_llm_table", 
    con=engine, 
    if_exists="replace", 
    index=False 
    )

2000